### PR TITLE
Update README.md in docs repo to point to docs website.

### PR DESCRIPTION
**Pull request by ed-harrison**

### CODE REVIEW

**Comment by ed-harrison** [comment]
I know we should retire this repo completely, but I've noticed we still have quite a lot of traffic coming here, so 
-  something must be pointing people here, so we shouldn't retire the repo until we work out what
-  we should make sure people are going to the right docs, not looking at what is still here.

**Comment by alexwlchan** [comment]
There are a couple of blog posts still pointing to the calico-docs repo; we should update their links to point to the ReadTheDocs pages: http://www.projectcalico.org/?s=https%3A%2F%2Fgithub.com%2FMetaswitch%2Fcalico-docs

I’ve also found a few references to the old repo in our current set of docs, and the main README in Metaswitch/Calico. Pull request to fix those shortly.

**Comment by ed-harrison** [comment]
Thanks Alex - I've updated all of the blog posts now.

**Comment by alexwlchan** [comment]
Right now the first thing anybody seems when they come to this repo is the README, which doesn’t give any indication that they’re in the wrong place.

Even if we don’t want to retire/delete the repo, can we merge this PR so that visitors go to the right place?

**Comment by ed-harrison** [comment]
Good point...

**Pull request merged**
